### PR TITLE
Fix Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "firebase-config-json" does not.  

### PR DESCRIPTION
**Pull request by purnamasari**
I was having the issue regarding variable name, and lookup about strapi that's integrated using graphql doesn't support '-' special character. If you don't mind changing the variable naming, to something like "firebase_config_json" or anything that doesn't contain '-', it will solve the graphql naming issue.

image

### CODE REVIEW

**Comment by espython** [comment]
@purnamasari thanks for your efforts we gonna review your pr and back to you

**Comment by otociulis** [comment]
+1 on this issue

**Comment by LuchoAGN** [comment]
+1 for this solution, I hope soon a solution for this case of having GRAPHQL installed.

**Comment by markkdev** [comment]
Hi any movement on this?

**Pull request merged**
